version: '3.3'
services:
  backend:
    image: dto80/se234-lab11:latest
    ports:
      - "8078:8080"
    volumes:
      - type: bind
        source: "C:/Users/DELL/Desktop/FirstSem/testData/data.xlsx"
        target:
  frontend:
    image: gloriawinnyunt/234-deploylab-frontend:latest
    ports:
      - "8077:80"
    
